backend:
  name: git-gateway
  repo: Twinpixel-nl/TwinPixel-Website
  branch: main

media_folder: "Images/uploads"
public_folder: "/Images/uploads"

site_url: https://twinpixel.nl

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publicatiedatum", name: "date", widget: "datetime" }
      - { label: "Omschrijving", name: "description", widget: "string" }
      - { label: "Inhoud", name: "body", widget: "markdown" }