backend:
  name: git-gateway
  repo: Twinpixel-nl/TwinPixel-Website
  branch: main

media_folder: "Images/uploads"
public_folder: "/Images/uploads"

site_url: https://twinpixel.nl
display_url: https://twinpixel.nl

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - {
          label: "Publicatiedatum",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DDTHH:mm:ss.SSSZ",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm",
        }
      - {
          label: "Korte Omschrijving (SEO)",
          name: "description",
          widget: "string",
        }
      - {
          label: "Uitgelichte Afbeelding",
          name: "image",
          widget: "image",
          required: false,
        }
      - { label: "Inhoud", name: "body", widget: "markdown" }

# Netlify build hook (optioneel, hoort normaal in netlify.toml)
build:
  publish: .
  functions: functions
  command: node js/sitegenerator.js

hooks:
  deploy: "https://api.netlify.com/build_hooks/abcdef12345678"
